#### general settings
name: ours
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [1]

sde:
  # max_sigma: 10
  max_sigma: 1
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/proj/image-restoration-sde-main/codes/datasets/lol_dataset/our485/high
    dataroot_LQ: /home/proj/image-restoration-sde-main/codes/datasets/lol_dataset/our485/low

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/proj/image-restoration-sde-main/codes/datasets/lol_dataset/eval15/high
    dataroot_LQ: /home/proj/image-restoration-sde-main/codes/datasets/lol_dataset/eval15/low

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: 1

#### logger
logger:
  print_freq: 1
  save_checkpoint_freq: 1
