#### general settings
name: ours
# name: ddpm
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [0]

sde:
  # max_sigma: 30
  max_sigma: 1
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # # for super-resolution
  # scale: 4
  scale: 1

  # for inpainting
  mask_root: /home/proj/image-restoration-sde-main/codes/config/inpainting/data/datasets/gt_keep_masks/thin # thick, thin, genhalf, ex64
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    # mode: GT
    # dataroot_GT: /home/ziwlu/datasets/celebaHQ/data256x256/trainHQ

    mode: GT
    dataroot_GT: /home/proj/image-restoration-sde-main/codes/datasets/celebaHQ/data256x256/trainHQ

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    # GT_size: 128
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    # mode: GT
    # dataroot_GT: /home/ziwlu/datasets/celebaHQ/data256x256/testHQ

    mode: LQGT
    dataroot_GT: /home/proj/image-restoration-sde-main/codes/datasets/celebaHQ/data256x256/testHQ
    dataroot_LQ: /home/proj/image-restoration-sde-main/codes/datasets/celebaHQ/data256x256/testLQ



### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4
    



#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  # niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e4
  # val_freq: !!float 100

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
